#pragma once

/* AI model configuration — auto-generated by STM32 AI Deployer */

#define AI_MODEL_NAME      "{{MODEL_NAME}}"
#define AI_SENSOR_TYPE     "{{SENSOR_TYPE}}"
#define AI_TARGET_BOARD    "{{BOARD_NAME}}"

/* STM32N6 has 4 MB RAM and integrated NPU */
#define AI_ACTIVATIONS_SIZE   (512 * 1024)
#define AI_INPUT_SIZE         (256)
#define AI_OUTPUT_CLASSES     (35)   /* KWS: 35 keyword classes */
