/* ai_runner.c — X-CUBE-AI inference wrapper
 * Wraps the generated network.c/network.h produced by stedgeai.
 * Auto-generated by STM32 AI Deployer.
 *
 * Requires X-CUBE-AI middleware headers in the include path.
 * The network C files (network.c, network.h, network_data.c) must be
 * copied to Src/ / Inc/ by PipelineRunner::stepPrepare().
 */

#include "ai_runner.h"
#include "ai_config.h"

/* X-CUBE-AI headers — provided by stedgeai generate output */
#include "network.h"
#include "network_data.h"

#include <string.h>

/* Static activation buffer — size comes from AI_ACTIVATIONS_SIZE in ai_config.h */
static uint8_t ai_activations[AI_ACTIVATIONS_SIZE] __attribute__((aligned(4)));

static ai_handle  s_network    = AI_HANDLE_NULL;
static ai_buffer  s_in_buffer[AI_NETWORK_IN_NUM];
static ai_buffer  s_out_buffer[AI_NETWORK_OUT_NUM];

/* DWT cycle counter helpers */
#ifndef DWT_CYCCNT
#define DWT_CYCCNT (*((volatile uint32_t *)0xE0001004))
#define DWT_CTRL   (*((volatile uint32_t *)0xE0001000))
#endif

static uint32_t dwt_us(uint32_t cycles)
{
    /* Assumes SystemCoreClock is set correctly */
    extern uint32_t SystemCoreClock;
    return (uint32_t)((uint64_t)cycles * 1000000UL / SystemCoreClock);
}

/* Class labels — customise for your model */
static const char *const CLASS_LABELS[AI_OUTPUT_CLASSES] = {
    "walking", "running", "sitting", "standing",
#if AI_OUTPUT_CLASSES > 4
    "lying", "cycling", "unknown", "idle",
#endif
};

/* ── Init ─────────────────────────────────────────────────────────────── */

void AI_Runner_Init(void)
{
    /* Enable DWT cycle counter */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT_CYCCNT = 0;
    DWT_CTRL  |= 1;

    const ai_handle network_data[] = { AI_NETWORK_DATA_WEIGHTS_GET() };

    ai_error err = ai_network_create_and_init(&s_network,
                                               network_data, NULL);
    (void)err;  /* NOTE: check err in production */

    /* Bind static activation buffer */
    ai_network_params params = {
        AI_NETWORK_DATA_WEIGHTS(AI_NETWORK_DATA_WEIGHTS_GET()),
        AI_NETWORK_DATA_ACTIVATIONS(ai_activations)
    };
    ai_network_init(s_network, &params);

    /* Get I/O buffer info */
    ai_network_inputs_get(s_network,  s_in_buffer);
    ai_network_outputs_get(s_network, s_out_buffer);
}

/* ── Infer ────────────────────────────────────────────────────────────── */

uint32_t AI_Runner_Infer(const float *input, AI_InferenceResult *result)
{
    /* Point input buffer to caller's data */
    s_in_buffer[0].data = (void *)input;

    /* Allocate output on stack */
    float output_data[AI_OUTPUT_CLASSES] = {0};
    s_out_buffer[0].data = output_data;

    uint32_t t0 = DWT_CYCCNT;
    ai_network_run(s_network, s_in_buffer, s_out_buffer);
    uint32_t elapsed_us = dwt_us(DWT_CYCCNT - t0);

    /* Argmax */
    uint8_t best = 0;
    float   best_val = output_data[0];
    for (int i = 1; i < AI_OUTPUT_CLASSES; i++) {
        if (output_data[i] > best_val) {
            best_val = output_data[i];
            best     = (uint8_t)i;
        }
    }

    result->class_id       = best;
    result->confidence_pct = (uint8_t)(best_val * 100.0f + 0.5f);
    if (best < AI_OUTPUT_CLASSES)
        strncpy(result->label, CLASS_LABELS[best], sizeof(result->label) - 1);
    else
        strncpy(result->label, "unknown", sizeof(result->label) - 1);

    return elapsed_us;
}

/* ── Memory helpers ───────────────────────────────────────────────────── */

uint32_t AI_Runner_GetRamUsage(void)
{
    return AI_ACTIVATIONS_SIZE;
}

uint32_t AI_Runner_GetFreeRam(void)
{
    /* Simple heap probe — not accurate under RTOS */
    extern uint8_t _end;
    extern uint8_t _estack;
    return (uint32_t)(&_estack - &_end);
}
