/* ai_runner.c — X-CUBE-AI inference wrapper
 * Wraps the generated network.c/network.h produced by stedgeai.
 * Auto-generated by STM32 AI Deployer.
 *
 * Requires X-CUBE-AI middleware headers in the include path.
 * The network C files (network.c, network.h, network_data.c) must be
 * copied to Src/ / Inc/ by PipelineRunner::stepPrepare().
 */

#include "ai_runner.h"
#include "ai_config.h"
#include "main.h"

/* X-CUBE-AI headers — provided by stedgeai generate output */
#include "network.h"
#include "network_data.h"
#include "network_data_params.h"

#include <string.h>

/* Static activation buffer — size comes from AI_ACTIVATIONS_SIZE in ai_config.h */
static uint8_t ai_activations[AI_ACTIVATIONS_SIZE] __attribute__((aligned(4)));

static ai_handle  s_network    = AI_HANDLE_NULL;
static ai_buffer *s_in_buffer   = NULL;
static ai_buffer *s_out_buffer  = NULL;

/* DWT cycle counter helpers */
#ifndef DWT_CYCCNT
#define DWT_CYCCNT (*((volatile uint32_t *)0xE0001004))
#define DWT_CTRL   (*((volatile uint32_t *)0xE0001000))
#endif

static uint32_t dwt_us(uint32_t cycles)
{
    /* Assumes SystemCoreClock is set correctly */
    extern uint32_t SystemCoreClock;
    return (uint32_t)((uint64_t)cycles * 1000000UL / SystemCoreClock);
}

/* Class labels — customise for your model */
static const char *const CLASS_LABELS[] = {
    "normal", "anomaly", "class_2", "class_3",
#if AI_OUTPUT_CLASSES > 4
    "class_4", "class_5", "class_6", "class_7",
#endif
};

/* ── Init ─────────────────────────────────────────────────────────────── */

void AI_Runner_Init(void)
{
    /* Enable DWT cycle counter */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT_CYCCNT = 0;
    DWT_CTRL  |= 1;

    ai_handle *activation_buffers = AI_NETWORK_DATA_ACTIVATIONS_TABLE_GET();
    activation_buffers[0] = AI_HANDLE_PTR(ai_activations);

    ai_error err = ai_network_create_and_init(&s_network,
                                               activation_buffers,
                                               NULL);
    (void)err;  /* NOTE: check err in production */

    /* Get I/O buffer info */
    s_in_buffer  = ai_network_inputs_get(s_network, NULL);
    s_out_buffer = ai_network_outputs_get(s_network, NULL);
}

/* ── Infer ────────────────────────────────────────────────────────────── */

uint32_t AI_Runner_Infer(const float *input, AI_InferenceResult *result)
{
    /* Point input buffer to caller's data */
    s_in_buffer[0].data = AI_HANDLE_PTR(input);

    /* Allocate output on stack */
    ai_i8 output_data[AI_NETWORK_OUT_1_SIZE] = {0};
    s_out_buffer[0].data = AI_HANDLE_PTR(output_data);

    uint32_t t0 = DWT_CYCCNT;
    ai_network_run(s_network, s_in_buffer, s_out_buffer);
    uint32_t elapsed_us = dwt_us(DWT_CYCCNT - t0);

    /* Argmax */
    uint8_t best = 0;
    ai_i8   best_val = output_data[0];
    for (int i = 1; i < AI_OUTPUT_CLASSES; i++) {
        if (output_data[i] > best_val) {
            best_val = output_data[i];
            best     = (uint8_t)i;
        }
    }

    int32_t confidence = ((int32_t)best_val + 128) * 100 / 255;
    if (confidence < 0) confidence = 0;
    if (confidence > 100) confidence = 100;

    result->class_id       = best;
    result->confidence_pct = (uint8_t)confidence;
    if (best < AI_OUTPUT_CLASSES)
        strncpy(result->label, CLASS_LABELS[best], sizeof(result->label) - 1);
    else
        strncpy(result->label, "unknown", sizeof(result->label) - 1);

    return elapsed_us;
}

/* ── Memory helpers ───────────────────────────────────────────────────── */

uint32_t AI_Runner_GetRamUsage(void)
{
    return AI_ACTIVATIONS_SIZE;
}

uint32_t AI_Runner_GetFreeRam(void)
{
    /* Simple heap probe — not accurate under RTOS */
    extern uint8_t _end;
    extern uint8_t _estack;
    return (uint32_t)(&_estack - &_end);
}
