/* ai_runner.c — X-CUBE-AI inference wrapper
 * Wraps the generated network.c/network.h produced by stedgeai.
 * Auto-generated by STM32 AI Deployer.
 *
 * Requires X-CUBE-AI middleware headers in the include path.
 * The network C files (network.c, network.h, network_data.c) must be
 * copied to Src/ / Inc/ by PipelineRunner::stepPrepare().
 */

#include "ai_runner.h"
#include "ai_config.h"
#include "main.h"

/* X-CUBE-AI headers — provided by stedgeai generate output */
#include "network.h"
#include "network_data.h"
#include "network_data_params.h"

#include <string.h>
#include <stdio.h>
#include <stdint.h>

/* Static activation buffer — size comes from AI_ACTIVATIONS_SIZE in ai_config.h */
static uint8_t ai_activations[AI_ACTIVATIONS_SIZE] __attribute__((aligned(4)));

static ai_handle  s_network    = AI_HANDLE_NULL;
static ai_buffer *s_in_buffer   = NULL;
static ai_buffer *s_out_buffer  = NULL;

/* DWT cycle counter helpers */
#ifndef DWT_CYCCNT
#define DWT_CYCCNT (*((volatile uint32_t *)0xE0001004))
#define DWT_CTRL   (*((volatile uint32_t *)0xE0001000))
#endif

static uint32_t dwt_us(uint32_t cycles)
{
    /* Assumes SystemCoreClock is set correctly */
    extern uint32_t SystemCoreClock;
    return (uint32_t)((uint64_t)cycles * 1000000UL / SystemCoreClock);
}

/* Class labels — customise for your model */
static const char *const CLASS_LABELS[] = {
    "normal", "anomaly", "class_2", "class_3",
#if AI_OUTPUT_CLASSES > 4
    "class_4", "class_5", "class_6", "class_7",
#endif
};

static int name_contains(const char *name, const char *needle)
{
    return strstr(name, needle) != NULL;
}

static ai_i8 clamp_i8(int32_t v)
{
    if (v > 127) return 127;
    if (v < -128) return -128;
    return (ai_i8)v;
}

static ai_i8 quantize_norm(float norm, float scale, int32_t zero_point)
{
    float q = (norm / scale) + (float)zero_point;
    int32_t qi = (int32_t)(q >= 0.0f ? q + 0.5f : q - 0.5f);
    return clamp_i8(qi);
}

static void prepare_s8_input(const float *input, ai_i8 *q_input)
{
    if (name_contains(AI_SENSOR_TYPE, "BME280") && name_contains(AI_MODEL_NAME, "anomaly")) {
        const float norm_t = (input[0] - 22.267314f) / 2.788822f;
        const float norm_h = (input[1] - 61.317606f) / 11.624848f;
        const float norm_c = 0.0f;
        q_input[0] = quantize_norm(norm_t, 0.037805241f, 45);
        q_input[1] = quantize_norm(norm_h, 0.037805241f, 45);
        q_input[2] = quantize_norm(norm_c, 0.037805241f, 45);
        return;
    }

    if (name_contains(AI_SENSOR_TYPE, "BME280") && name_contains(AI_MODEL_NAME, "weather")) {
        const float norm_t = (input[0] - 19.080682f) / 17.331159f;
        const float norm_h = (input[1] - 68.559091f) / 20.172474f;
        const float norm_p = (input[2] - 1005.656206f) / 37.311331f;
        q_input[0] = quantize_norm(norm_t, 0.030175343f, -26);
        q_input[1] = quantize_norm(norm_h, 0.030175343f, -26);
        q_input[2] = quantize_norm(norm_p, 0.030175343f, -26);
        return;
    }

    for (uint32_t i = 0; i < AI_INPUT_SIZE; ++i) {
        q_input[i] = clamp_i8((int32_t)(input[i] >= 0.0f ? input[i] + 0.5f : input[i] - 0.5f));
    }
}

/* ── Init ─────────────────────────────────────────────────────────────── */

void AI_Runner_Init(void)
{
    /* Enable DWT cycle counter */
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT_CYCCNT = 0;
    DWT_CTRL  |= 1;

    ai_handle *activation_buffers = AI_NETWORK_DATA_ACTIVATIONS_TABLE_GET();
    activation_buffers[0] = AI_HANDLE_PTR(ai_activations);

    ai_error err = ai_network_create_and_init(&s_network,
                                               activation_buffers,
                                               NULL);
    (void)err;  /* NOTE: check err in production */

    /* Get I/O buffer info */
    s_in_buffer  = ai_network_inputs_get(s_network, NULL);
    s_out_buffer = ai_network_outputs_get(s_network, NULL);
}

/* ── Infer ────────────────────────────────────────────────────────────── */

uint32_t AI_Runner_Infer(const float *input, AI_InferenceResult *result)
{
#if defined(AI_NETWORK_IN_1_FORMAT) && (AI_NETWORK_IN_1_FORMAT == AI_BUFFER_FORMAT_S8)
    ai_i8 q_input[AI_NETWORK_IN_1_SIZE] = {0};
    prepare_s8_input(input, q_input);
    s_in_buffer[0].data = AI_HANDLE_PTR(q_input);
#else
    /* Point input buffer to caller's data */
    s_in_buffer[0].data = AI_HANDLE_PTR(input);
#endif

    /* Allocate output on stack */
    ai_i8 output_data[AI_NETWORK_OUT_1_SIZE] = {0};
    s_out_buffer[0].data = AI_HANDLE_PTR(output_data);

    uint32_t t0 = DWT_CYCCNT;
    ai_network_run(s_network, s_in_buffer, s_out_buffer);
    uint32_t elapsed_us = dwt_us(DWT_CYCCNT - t0);

    /* Argmax */
    uint8_t best = 0;
    ai_i8   best_val = output_data[0];
    for (int i = 1; i < AI_OUTPUT_CLASSES; i++) {
        if (output_data[i] > best_val) {
            best_val = output_data[i];
            best     = (uint8_t)i;
        }
    }

    int32_t confidence = ((int32_t)best_val + 128) * 100 / 255;
    if (confidence < 0) confidence = 0;
    if (confidence > 100) confidence = 100;

    result->class_id       = best;
    result->confidence_pct = (uint8_t)confidence;
    if (best < (sizeof(CLASS_LABELS) / sizeof(CLASS_LABELS[0]))) {
        strncpy(result->label, CLASS_LABELS[best], sizeof(result->label) - 1);
        result->label[sizeof(result->label) - 1] = '\0';
    } else {
        snprintf(result->label, sizeof(result->label), "class_%u", (unsigned)best);
    }

    return elapsed_us;
}

/* ── Memory helpers ───────────────────────────────────────────────────── */

uint32_t AI_Runner_GetRamUsage(void)
{
    return AI_ACTIVATIONS_SIZE;
}

uint32_t AI_Runner_GetFreeRam(void)
{
    /* Simple heap probe — not accurate under RTOS */
    extern uint8_t _end;
    extern uint8_t _estack;
    return (uint32_t)(&_estack - &_end);
}
