/* uart_report.c — Protocol v1.0 UART reporter
 * Format: §{JSON}\r\n
 * §  = UTF-8 0xC2 0xA7 (start marker)
 * All numeric values are integer — no float/printf %f
 * Transmission: HAL_UART_Transmit (blocking, DMA variant if available)
 * Auto-generated by STM32 AI Deployer.
 */

#include "uart_report.h"

#include "ai_config.h"
#include "main.h"
#include <stdio.h>
#include <string.h>

/* § start marker bytes */
#define PROTO_MARKER_B0  0xC2u
#define PROTO_MARKER_B1  0xA7u
#define UART_TX_TIMEOUT  50   /* ms */

#ifndef AI_BOARD_FLASH_KB
#define AI_BOARD_FLASH_KB  0U
#endif
#ifndef AI_BOARD_RAM_KB
#define AI_BOARD_RAM_KB    0U
#endif
#ifndef AI_BOARD_CLOCK_MHZ
#define AI_BOARD_CLOCK_MHZ 0U
#endif

static UART_HandleTypeDef *s_huart = NULL;

/* ── Internal send ────────────────────────────────────────────────────── */

static void send_packet(const char *json)
{
    if (!s_huart) return;

    /* Build: §{json}\r\n */
    static uint8_t buf[256];
    uint16_t       len = 0;

    buf[len++] = PROTO_MARKER_B0;
    buf[len++] = PROTO_MARKER_B1;

    uint16_t jlen = (uint16_t)strlen(json);
    if (jlen > sizeof(buf) - 4) jlen = sizeof(buf) - 4;
    memcpy(&buf[len], json, jlen);
    len += jlen;
    buf[len++] = '\r';
    buf[len++] = '\n';

    HAL_UART_Transmit(s_huart, buf, len, UART_TX_TIMEOUT);
}

/* ── Public API ───────────────────────────────────────────────────────── */

void UART_Report_SetHandle(void *huart)
{
    s_huart = (UART_HandleTypeDef *)huart;
}

void UART_Report_Boot(const char *model,
                      const char *card,
                      const char *sdk,
                      uint32_t    baud)
{
    char json[240];
    snprintf(json, sizeof(json),
             "{\"t\":\"boot\",\"card\":\"%s\",\"sdk\":\"%s\","
             "\"model\":\"%s\",\"sensor\":\"%s\",\"baud\":%lu,"
             "\"flash_kb\":%lu,\"ram_kb\":%lu,\"clock_mhz\":%lu}",
             card, sdk, model, AI_SENSOR_TYPE, (unsigned long)baud,
             (unsigned long)AI_BOARD_FLASH_KB,
             (unsigned long)AI_BOARD_RAM_KB,
             (unsigned long)AI_BOARD_CLOCK_MHZ);
    send_packet(json);
}

void UART_Report_Inference(const char *model,
                           uint32_t    inf_us,
                           uint32_t    ram_b,
                           uint8_t     acc_pct,
                           const char *label,
                           const char *card)
{
    char json[200];
    snprintf(json, sizeof(json),
             "{\"t\":\"inf\",\"model\":\"%s\",\"inf_us\":%lu,"
             "\"ram_b\":%lu,\"acc_pct\":%u,\"label\":\"%s\","
             "\"card\":\"%s\"}",
             model, (unsigned long)inf_us, (unsigned long)ram_b,
             (unsigned)acc_pct, label, card);
    send_packet(json);
}

void UART_Report_SysStatus(uint32_t    uptime_s,
                           int32_t     temp_c,
                           uint32_t    free_ram_b,
                           const char *state)
{
    char json[150];
    snprintf(json, sizeof(json),
             "{\"t\":\"sys\",\"uptime_s\":%lu,\"temp_c\":%ld,"
             "\"free_ram_b\":%lu,\"state\":\"%s\"}",
             (unsigned long)uptime_s, (long)temp_c,
             (unsigned long)free_ram_b, state);
    send_packet(json);
}

void UART_Report_Error(uint32_t code, const char *msg)
{
    char json[120];
    snprintf(json, sizeof(json),
             "{\"t\":\"err\",\"code\":%lu,\"msg\":\"%s\"}",
             (unsigned long)code, msg);
    send_packet(json);
}

void UART_Report_Benchmark(const char *model,
                           uint32_t samples,
                           uint32_t avg_us,
                           uint32_t min_us,
                           uint32_t max_us,
                           uint32_t ram_b,
                           uint32_t free_ram_b,
                           const char *label,
                           const char *card)
{
    char json[240];
    snprintf(json, sizeof(json),
             "{\"t\":\"bench\",\"model\":\"%s\",\"samples\":%lu,\"avg_us\":%lu,"
             "\"min_us\":%lu,\"max_us\":%lu,\"ram_b\":%lu,"
             "\"free_ram_b\":%lu,\"label\":\"%s\",\"card\":\"%s\"}",
             model,
             (unsigned long)samples,
             (unsigned long)avg_us,
             (unsigned long)min_us,
             (unsigned long)max_us,
             (unsigned long)ram_b,
             (unsigned long)free_ram_b,
             label,
             card);
    send_packet(json);
}

void UART_Report_Sensor(const char *sensor,
                        uint32_t seq,
                        int32_t value0,
                        int32_t value1,
                        int32_t value2,
                        const char *unit,
                        const char *model,
                        uint32_t inf_us,
                        uint32_t ram_b,
                        uint8_t acc_pct,
                        const char *label,
                        const char *card)
{
    char json[256];
    snprintf(json, sizeof(json),
             "{\"t\":\"sensor\",\"sensor\":\"%s\",\"seq\":%lu,"
             "\"values\":[%ld,%ld,%ld],\"unit\":\"%s\","
             "\"model\":\"%s\",\"inf_us\":%lu,\"ram_b\":%lu,"
             "\"acc_pct\":%u,\"label\":\"%s\",\"card\":\"%s\"}",
             sensor,
             (unsigned long)seq,
             (long)value0,
             (long)value1,
             (long)value2,
             unit,
             model,
             (unsigned long)inf_us,
             (unsigned long)ram_b,
             (unsigned)acc_pct,
             label,
             card);
    send_packet(json);
}
