/* bme280.c — BME280 I2C driver (temperature / pressure / humidity)
 * Protocol: I2C @ {{I2C_INSTANCE}}, SDA={{SDA_PORT}} {{SDA_PIN}}, SCL={{SCL_PORT}} {{SCL_PIN}}
 * Address : {{I2C_ADDRESS}}
 * Auto-generated by STM32 AI Deployer.
 *
 * NOTE: Full compensation formulas from Bosch datasheet BST-BME280-DS002.
 *       Trim values are read from device NVM on init.
 */

#include "bme280.h"
#include <string.h>

static I2C_HandleTypeDef *s_hi2c = NULL;

/* Calibration data */
static uint16_t dig_T1;
static int16_t  dig_T2, dig_T3;
static uint16_t dig_P1;
static int16_t  dig_P2, dig_P3, dig_P4, dig_P5, dig_P6, dig_P7, dig_P8, dig_P9;
static uint8_t  dig_H1;
static int16_t  dig_H2;
static uint8_t  dig_H3;
static int16_t  dig_H4, dig_H5;
static int8_t   dig_H6;
static int32_t  t_fine;

/* ── Init ─────────────────────────────────────────────────────────────── */

HAL_StatusTypeDef BME280_Init(I2C_HandleTypeDef *hi2c)
{
    uint8_t chip_id = 0;
    HAL_StatusTypeDef ret;

    ret = HAL_I2C_Mem_Read(hi2c, BME280_I2C_ADDR, BME280_REG_CHIP_ID,
                           I2C_MEMADD_SIZE_8BIT, &chip_id, 1, 100);
    if (ret != HAL_OK || chip_id != BME280_CHIP_ID_VAL) return HAL_ERROR;

    /* Read calibration data — registers 0x88..0xA1 and 0xE1..0xE7 */
    uint8_t calib[26];
    ret = HAL_I2C_Mem_Read(hi2c, BME280_I2C_ADDR, 0x88,
                           I2C_MEMADD_SIZE_8BIT, calib, 26, 100);
    if (ret != HAL_OK) return ret;

    dig_T1 = (uint16_t)(calib[1]  << 8 | calib[0]);
    dig_T2 = (int16_t) (calib[3]  << 8 | calib[2]);
    dig_T3 = (int16_t) (calib[5]  << 8 | calib[4]);
    dig_P1 = (uint16_t)(calib[7]  << 8 | calib[6]);
    dig_P2 = (int16_t) (calib[9]  << 8 | calib[8]);
    dig_P3 = (int16_t) (calib[11] << 8 | calib[10]);
    dig_P4 = (int16_t) (calib[13] << 8 | calib[12]);
    dig_P5 = (int16_t) (calib[15] << 8 | calib[14]);
    dig_P6 = (int16_t) (calib[17] << 8 | calib[16]);
    dig_P7 = (int16_t) (calib[19] << 8 | calib[18]);
    dig_P8 = (int16_t) (calib[21] << 8 | calib[20]);
    dig_P9 = (int16_t) (calib[23] << 8 | calib[22]);
    dig_H1 = calib[25];

    /* Set oversampling: T×2, P×16, H×1; normal mode */
    uint8_t ctrl = 0x01; /* H oversample ×1 */
    HAL_I2C_Mem_Write(hi2c, BME280_I2C_ADDR, BME280_REG_CTRL_HUM,
                      I2C_MEMADD_SIZE_8BIT, &ctrl, 1, 100);

    ctrl = 0xB7; /* T×2 P×16 normal mode */
    HAL_I2C_Mem_Write(hi2c, BME280_I2C_ADDR, BME280_REG_CTRL_MEAS,
                      I2C_MEMADD_SIZE_8BIT, &ctrl, 1, 100);

    return HAL_OK;
}

/* ── Read ─────────────────────────────────────────────────────────────── */

HAL_StatusTypeDef BME280_ReadAll(I2C_HandleTypeDef *hi2c, BME280_Data *data)
{
    uint8_t raw[8];
    HAL_StatusTypeDef ret = HAL_I2C_Mem_Read(
        hi2c, BME280_I2C_ADDR, BME280_REG_PRESS_MSB,
        I2C_MEMADD_SIZE_8BIT, raw, 8, 100);
    if (ret != HAL_OK) return ret;

    int32_t adc_P = (int32_t)(((uint32_t)raw[0] << 12) | ((uint32_t)raw[1] << 4) | (raw[2] >> 4));
    int32_t adc_T = (int32_t)(((uint32_t)raw[3] << 12) | ((uint32_t)raw[4] << 4) | (raw[5] >> 4));
    int32_t adc_H = (int32_t)(((uint32_t)raw[6] << 8)  |  (uint32_t)raw[7]);

    /* Temperature */
    int32_t var1 = (((adc_T >> 3) - ((int32_t)dig_T1 << 1)) * (int32_t)dig_T2) >> 11;
    int32_t var2 = (((((adc_T >> 4) - (int32_t)dig_T1) * ((adc_T >> 4) - (int32_t)dig_T1)) >> 12) * (int32_t)dig_T3) >> 14;
    t_fine = var1 + var2;
    data->temperature_c = (float)((t_fine * 5 + 128) >> 8) / 100.0f;

    /* Pressure (simplified) */
    int64_t v1 = ((int64_t)t_fine) - 128000;
    int64_t v2 = v1 * v1 * (int64_t)dig_P6;
    v2 = v2 + ((v1 * (int64_t)dig_P5) << 17);
    v2 = v2 + (((int64_t)dig_P4) << 35);
    v1 = ((v1 * v1 * (int64_t)dig_P3) >> 8) + ((v1 * (int64_t)dig_P2) << 12);
    v1 = (((int64_t)1 << 47) + v1) * ((int64_t)dig_P1) >> 33;
    if (v1 == 0) { data->pressure_hpa = 0.0f; }
    else {
        int64_t p = 1048576 - adc_P;
        p = (((p << 31) - v2) * 3125) / v1;
        v1 = ((int64_t)dig_P9 * (p >> 13) * (p >> 13)) >> 25;
        v2 = ((int64_t)dig_P8 * p) >> 19;
        p = ((p + v1 + v2) >> 8) + ((int64_t)dig_P7 << 4);
        data->pressure_hpa = (float)p / 25600.0f;
    }

    /* Humidity */
    int32_t x = t_fine - 76800;
    x = (((((adc_H << 14) - ((int32_t)dig_H4 << 20) - ((int32_t)dig_H5 * x)) +
           16384) >> 15) *
         (((((((x * (int32_t)dig_H6) >> 10) *
              (((x * (int32_t)dig_H3) >> 11) + 32768)) >> 10) + 2097152) *
           (int32_t)dig_H2 + 8192) >> 14));
    x = x - (((((x >> 15) * (x >> 15)) >> 7) * (int32_t)dig_H1) >> 4);
    x = x < 0 ? 0 : (x > 419430400 ? 419430400 : x);
    data->humidity_pct = (float)(x >> 12) / 1024.0f;

    return HAL_OK;
}

/* ── Generic Sensor API ───────────────────────────────────────────────── */

void Sensor_Init(I2C_HandleTypeDef *hi2c)
{
    s_hi2c = hi2c;
    BME280_Init(hi2c);
}

void Sensor_Read(float *out, uint16_t len)
{
    BME280_Data d = {0};
    if (s_hi2c) BME280_ReadAll(s_hi2c, &d);

    float vals[3] = { d.temperature_c, d.pressure_hpa, d.humidity_pct };
    for (uint16_t i = 0; i < len; i++)
        out[i] = vals[i % 3];
}
