#pragma once

/* AI model configuration - auto-generated by STM32 AI Deployer */

#define AI_MODEL_NAME      "{{MODEL_NAME}}"
#define AI_SENSOR_TYPE     "{{SENSOR_TYPE}}"
#define AI_TARGET_BOARD    "{{BOARD_NAME}}"

#if __has_include("network.h")
#include "network.h"
#endif

#if __has_include("network_data_params.h")
#include "network_data_params.h"
#endif

#ifdef AI_NETWORK_DATA_ACTIVATIONS_SIZE
#define AI_ACTIVATIONS_SIZE   AI_NETWORK_DATA_ACTIVATIONS_SIZE
#else
#define AI_ACTIVATIONS_SIZE   (32 * 1024)
#endif

#ifdef AI_NETWORK_IN_1_SIZE
#define AI_INPUT_SIZE         AI_NETWORK_IN_1_SIZE
#else
#define AI_INPUT_SIZE         (128)
#endif

#ifdef AI_NETWORK_OUT_1_SIZE
#define AI_OUTPUT_CLASSES     AI_NETWORK_OUT_1_SIZE
#else
#define AI_OUTPUT_CLASSES     (4)
#endif
