#pragma once

/* AI model configuration — auto-generated by STM32 AI Deployer */

#define AI_MODEL_NAME      "{{MODEL_NAME}}"
#define AI_SENSOR_TYPE     "{{SENSOR_TYPE}}"
#define AI_TARGET_BOARD    "{{BOARD_NAME}}"

/* STM32H7 has 1 MB RAM — larger activation buffer possible */
#define AI_ACTIVATIONS_SIZE   (128 * 1024)
#define AI_INPUT_SIZE         (128)
#define AI_OUTPUT_CLASSES     (4)
