/* main.c — {{MODEL_NAME}} on {{BOARD_NAME}}
 * Auto-generated by STM32 AI Deployer. Customise as needed.
 */

#include "main.h"
#include "ai_config.h"
#include "ai_runner.h"
#include "uart_report.h"
#include "{{SENSOR_TYPE_LOWER}}.h"

#include <stdio.h>
#include <string.h>

/* Private variables */
UART_HandleTypeDef huart2;
I2C_HandleTypeDef  hi2c1;

/* Private function prototypes */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_I2C1_Init(void);
static void Process_Uart_Command(void);
static void Run_Benchmark(uint32_t samples, float min_v, float max_v, uint32_t seed);

static char s_cmd_buf[96];
static uint8_t s_cmd_len = 0;
static volatile uint8_t s_cmd_ready = 0;
static uint8_t s_rx_byte = 0;

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_I2C1_Init();

    /* Initialise sensor */
    Sensor_Init(&hi2c1);

    /* Initialise AI model */
    AI_Runner_Init();
    UART_Report_SetHandle(&huart2);
    HAL_UART_Receive_IT(&huart2, &s_rx_byte, 1);

    /* Report boot event */
    UART_Report_Boot(AI_MODEL_NAME, AI_TARGET_BOARD, "EdgeAI_v1.0", 115200);

    uint32_t cycle = 0;

    while (1)
    {
        Process_Uart_Command();

        /* Read sensor data */
        float input[AI_INPUT_SIZE];
        if (Sensor_Read(input, AI_INPUT_SIZE) != HAL_OK) {
            HAL_Delay(200);
            continue;
        }

        /* Run inference */
        AI_InferenceResult result;
        uint32_t inf_us = AI_Runner_Infer(input, &result);

        /* Report inference metrics via UART */
        UART_Report_Inference(AI_MODEL_NAME, inf_us,
                              AI_Runner_GetRamUsage(),
                              result.confidence_pct,
                              result.label,
                              AI_TARGET_BOARD);

        /* Periodic system status (every 60 inference cycles ≈ 1 Hz at 60 Hz) */
        if (++cycle % 60 == 0) {
            UART_Report_SysStatus(cycle / 60,
                                  /* temp_c  */ 0,
                                  AI_Runner_GetFreeRam(),
                                  "running");
        }

        HAL_Delay(16); /* ~60 Hz acquisition loop */
    }
}

/* ── Clock configuration — 168 MHz from 8 MHz HSE ─────────────────────── */

static uint32_t bench_rand(uint32_t *state)
{
    *state = (*state * 1664525UL) + 1013904223UL;
    return *state;
}

static void Run_Benchmark(uint32_t samples, float min_v, float max_v, uint32_t seed)
{
    if (samples == 0) samples = 1;
    if (samples > 10000) samples = 10000;
    if (max_v < min_v) {
        float tmp = min_v;
        min_v = max_v;
        max_v = tmp;
    }

    uint32_t total_us = 0;
    uint32_t min_us = 0xFFFFFFFFUL;
    uint32_t max_us = 0;
    AI_InferenceResult result = {0};
    float input[AI_INPUT_SIZE];
    uint32_t rng = seed ? seed : 1;

    for (uint32_t i = 0; i < samples; ++i) {
        for (uint32_t j = 0; j < AI_INPUT_SIZE; ++j) {
            uint32_t r = bench_rand(&rng);
            float unit = (float)(r & 0x00FFFFFFUL) / 16777215.0f;
            input[j] = min_v + unit * (max_v - min_v);
        }

        uint32_t inf_us = AI_Runner_Infer(input, &result);
        total_us += inf_us;
        if (inf_us < min_us) min_us = inf_us;
        if (inf_us > max_us) max_us = inf_us;
    }

    UART_Report_Benchmark(AI_MODEL_NAME,
                          samples,
                          total_us / samples,
                          min_us,
                          max_us,
                          AI_Runner_GetRamUsage(),
                          AI_Runner_GetFreeRam(),
                          result.label,
                          AI_TARGET_BOARD);
}

static void Process_Uart_Command(void)
{
    if (!s_cmd_ready)
        return;

    char cmd[96];
    __disable_irq();
    memcpy(cmd, s_cmd_buf, sizeof(cmd));
    s_cmd_ready = 0;
    __enable_irq();

    unsigned long samples = 20;
    long min_milli = 0;
    long max_milli = 1000;
    unsigned long seed = 1234;
    if (sscanf(cmd, "BENCH %lu %ld %ld %lu",
               &samples, &min_milli, &max_milli, &seed) >= 1) {
        Run_Benchmark((uint32_t)samples,
                      (float)min_milli / 1000.0f,
                      (float)max_milli / 1000.0f,
                      (uint32_t)seed);
    } else if (strcmp(cmd, "INFO?") == 0 || strcmp(cmd, "BOOT?") == 0) {
        UART_Report_Boot(AI_MODEL_NAME, AI_TARGET_BOARD, "EdgeAI_v1.0", 115200);
    }
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART2) {
        char ch = (char)s_rx_byte;
        if (!s_cmd_ready) {
            if (ch == '\r' || ch == '\n') {
                if (s_cmd_len > 0) {
                    s_cmd_buf[s_cmd_len] = '\0';
                    s_cmd_len = 0;
                    s_cmd_ready = 1;
                }
            } else if (s_cmd_len < sizeof(s_cmd_buf) - 1) {
                s_cmd_buf[s_cmd_len++] = ch;
            } else {
                s_cmd_len = 0;
            }
        }
        HAL_UART_Receive_IT(&huart2, &s_rx_byte, 1);
    }
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART2) {
        s_cmd_len = 0;
        HAL_UART_Receive_IT(&huart2, &s_rx_byte, 1);
    }
}

static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    osc.OscillatorType  = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState        = RCC_HSE_ON;
    osc.PLL.PLLState    = RCC_PLL_ON;
    osc.PLL.PLLSource   = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM        = 8;
    osc.PLL.PLLN        = 336;
    osc.PLL.PLLP        = RCC_PLLP_DIV2;
    osc.PLL.PLLQ        = 7;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    RCC_ClkInitTypeDef clk = {0};
    clk.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                         RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;
    clk.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5) != HAL_OK) Error_Handler();
}

/* ── GPIO init ─────────────────────────────────────────────────────────── */

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = LED_PIN;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_PORT, &gpio);
}

/* ── USART2 init — 115200, 8N1, DMA TX ────────────────────────────────── */

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) Error_Handler();
}

/* ── I2C1 init — 400 kHz fast mode ────────────────────────────────────── */

static void MX_I2C1_Init(void)
{
    hi2c1.Instance             = {{I2C_INSTANCE}};
    hi2c1.Init.ClockSpeed      = 400000;
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) Error_Handler();
}

/* ── Error handler ─────────────────────────────────────────────────────── */

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}
