/* main.c — {{MODEL_NAME}} on {{BOARD_NAME}}
 * Auto-generated by STM32 AI Deployer. Customise as needed.
 */

#include "main.h"
#include "ai_config.h"
#include "ai_runner.h"
#include "uart_report.h"
#include "{{SENSOR_TYPE_LOWER}}.h"

/* Private variables */
UART_HandleTypeDef huart2;
I2C_HandleTypeDef  hi2c1;

/* Private function prototypes */
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_I2C1_Init(void);

int main(void)
{
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART2_UART_Init();
    MX_I2C1_Init();

    /* Initialise sensor */
    Sensor_Init(&hi2c1);

    /* Initialise AI model */
    AI_Runner_Init();

    /* Report boot event */
    UART_Report_Boot(AI_MODEL_NAME, AI_TARGET_BOARD, "EdgeAI_v1.0", 115200);

    uint32_t cycle = 0;

    while (1)
    {
        /* Read sensor data */
        float input[AI_INPUT_SIZE];
        Sensor_Read(input, AI_INPUT_SIZE);

        /* Run inference */
        AI_InferenceResult result;
        uint32_t inf_us = AI_Runner_Infer(input, &result);

        /* Report inference metrics via UART */
        UART_Report_Inference(AI_MODEL_NAME, inf_us,
                              AI_Runner_GetRamUsage(),
                              result.confidence_pct,
                              result.label,
                              AI_TARGET_BOARD);

        /* Periodic system status (every 60 inference cycles ≈ 1 Hz at 60 Hz) */
        if (++cycle % 60 == 0) {
            UART_Report_SysStatus(cycle / 60,
                                  /* temp_c  */ 0,
                                  AI_Runner_GetFreeRam(),
                                  "running");
        }

        HAL_Delay(16); /* ~60 Hz acquisition loop */
    }
}

/* ── Clock configuration — 168 MHz from 8 MHz HSE ─────────────────────── */

static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    osc.OscillatorType  = RCC_OSCILLATORTYPE_HSE;
    osc.HSEState        = RCC_HSE_ON;
    osc.PLL.PLLState    = RCC_PLL_ON;
    osc.PLL.PLLSource   = RCC_PLLSOURCE_HSE;
    osc.PLL.PLLM        = 8;
    osc.PLL.PLLN        = 336;
    osc.PLL.PLLP        = RCC_PLLP_DIV2;
    osc.PLL.PLLQ        = 7;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    RCC_ClkInitTypeDef clk = {0};
    clk.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                         RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
    clk.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    clk.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    clk.APB1CLKDivider = RCC_HCLK_DIV4;
    clk.APB2CLKDivider = RCC_HCLK_DIV2;
    if (HAL_RCC_ClockConfig(&clk, FLASH_LATENCY_5) != HAL_OK) Error_Handler();
}

/* ── GPIO init ─────────────────────────────────────────────────────────── */

static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = LED_PIN;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_PORT, &gpio);
}

/* ── USART2 init — 115200, 8N1, DMA TX ────────────────────────────────── */

static void MX_USART2_UART_Init(void)
{
    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    if (HAL_UART_Init(&huart2) != HAL_OK) Error_Handler();
}

/* ── I2C1 init — 400 kHz fast mode ────────────────────────────────────── */

static void MX_I2C1_Init(void)
{
    hi2c1.Instance             = {{I2C_INSTANCE}};
    hi2c1.Init.ClockSpeed      = 400000;
    hi2c1.Init.DutyCycle       = I2C_DUTYCYCLE_2;
    hi2c1.Init.OwnAddress1     = 0;
    hi2c1.Init.AddressingMode  = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode   = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) Error_Handler();
}

/* ── Error handler ─────────────────────────────────────────────────────── */

void Error_Handler(void)
{
    __disable_irq();
    while (1) {}
}
