/* mpu6050.c — MPU-6050 I2C driver
 * Sensor  : InvenSense MPU-6050 (6-DoF IMU)
 * Protocol: I2C @ {{I2C_INSTANCE}}, SDA={{SDA_PORT}} {{SDA_PIN}}, SCL={{SCL_PORT}} {{SCL_PIN}}
 * Address : {{I2C_ADDRESS}}
 * Auto-generated by STM32 AI Deployer.
 */

#include "mpu6050.h"
#include <string.h>

static I2C_HandleTypeDef *s_hi2c = NULL;

/* ── Init ─────────────────────────────────────────────────────────────── */

HAL_StatusTypeDef MPU6050_Init(I2C_HandleTypeDef *hi2c)
{
    uint8_t data;
    HAL_StatusTypeDef ret;

    /* Wake up: clear SLEEP bit */
    data = 0x00;
    ret = HAL_I2C_Mem_Write(hi2c, MPU6050_I2C_ADDR, MPU6050_REG_PWR_MGMT_1,
                            I2C_MEMADD_SIZE_8BIT, &data, 1, 100);
    if (ret != HAL_OK) return ret;

    /* Sample rate divider: 0 → 1 kHz / (1+0) = 1 kHz */
    data = 0x00;
    ret = HAL_I2C_Mem_Write(hi2c, MPU6050_I2C_ADDR, MPU6050_REG_SMPLRT_DIV,
                            I2C_MEMADD_SIZE_8BIT, &data, 1, 100);
    if (ret != HAL_OK) return ret;

    /* DLPF: bandwidth 42 Hz */
    data = 0x03;
    ret = HAL_I2C_Mem_Write(hi2c, MPU6050_I2C_ADDR, MPU6050_REG_CONFIG,
                            I2C_MEMADD_SIZE_8BIT, &data, 1, 100);
    if (ret != HAL_OK) return ret;

    /* Gyro: ±250 °/s */
    data = 0x00;
    ret = HAL_I2C_Mem_Write(hi2c, MPU6050_I2C_ADDR, MPU6050_REG_GYRO_CONFIG,
                            I2C_MEMADD_SIZE_8BIT, &data, 1, 100);
    if (ret != HAL_OK) return ret;

    /* Accel: ±2 g */
    data = 0x00;
    ret = HAL_I2C_Mem_Write(hi2c, MPU6050_I2C_ADDR, MPU6050_REG_ACCEL_CONFIG,
                            I2C_MEMADD_SIZE_8BIT, &data, 1, 100);
    return ret;
}

/* ── Read ─────────────────────────────────────────────────────────────── */

HAL_StatusTypeDef MPU6050_ReadAll(I2C_HandleTypeDef *hi2c, MPU6050_Data *data)
{
    uint8_t raw[14];
    HAL_StatusTypeDef ret = HAL_I2C_Mem_Read(
        hi2c, MPU6050_I2C_ADDR, MPU6050_REG_ACCEL_XOUT_H,
        I2C_MEMADD_SIZE_8BIT, raw, 14, 100);
    if (ret != HAL_OK) return ret;

    int16_t ax_raw = (int16_t)((raw[0]  << 8) | raw[1]);
    int16_t ay_raw = (int16_t)((raw[2]  << 8) | raw[3]);
    int16_t az_raw = (int16_t)((raw[4]  << 8) | raw[5]);
    int16_t gx_raw = (int16_t)((raw[8]  << 8) | raw[9]);
    int16_t gy_raw = (int16_t)((raw[10] << 8) | raw[11]);
    int16_t gz_raw = (int16_t)((raw[12] << 8) | raw[13]);

    data->ax = ax_raw * MPU6050_ACCEL_SCALE;
    data->ay = ay_raw * MPU6050_ACCEL_SCALE;
    data->az = az_raw * MPU6050_ACCEL_SCALE;
    data->gx = gx_raw * MPU6050_GYRO_SCALE;
    data->gy = gy_raw * MPU6050_GYRO_SCALE;
    data->gz = gz_raw * MPU6050_GYRO_SCALE;

    return HAL_OK;
}

/* ── Generic Sensor API ───────────────────────────────────────────────── */

void Sensor_Init(I2C_HandleTypeDef *hi2c)
{
    s_hi2c = hi2c;
    MPU6050_Init(hi2c);
}

void Sensor_Read(float *out, uint16_t len)
{
    MPU6050_Data d = {0};
    if (s_hi2c) MPU6050_ReadAll(s_hi2c, &d);

    /* Fill output: [ax, ay, az, gx, gy, gz, ...] cycled */
    float vals[6] = { d.ax, d.ay, d.az, d.gx, d.gy, d.gz };
    for (uint16_t i = 0; i < len; i++)
        out[i] = vals[i % 6];
}
