/* main.c - {{MODEL_NAME}} on {{BOARD_NAME}}
 * Auto-generated by STM32 AI Deployer for STM32N657x0 (Cortex-M55 + NPU).
 */

#include "main.h"
#include "ai_config.h"
#include "ai_runner.h"
#include "uart_report.h"
#include "{{SENSOR_TYPE_LOWER}}.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

UART_HandleTypeDef huart1;
I2C_HandleTypeDef  hi2c1;

static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_USART1_UART_Init(void);
static void MX_I2C1_Init(void);
static void Ensure_AI_Ready(void);
static void Poll_Uart_Command(void);
static void Feed_Uart_Byte(uint8_t byte);
static void Process_Uart_Command(void);
static void Run_Benchmark(uint32_t samples, float min_v, float max_v, uint32_t seed);
static void Run_Manual_Inference(const char *payload);

static char     s_cmd_buf[96];
static uint8_t  s_cmd_len    = 0;
static volatile uint8_t s_cmd_ready = 0;
static uint8_t  s_rx_byte    = 0;
static uint8_t  s_ai_ready   = 0;

int main(void)
{
    SCB->CPACR |= ((3UL << 20U) | (3UL << 22U));
    __DSB();
    __ISB();
    __set_PRIMASK(0);
    __set_FAULTMASK(0);
    __set_BASEPRI(0);
    __enable_irq();

    /* Enable I-Cache and D-Cache (required for N6 performance) */
    SCB_EnableICache();
    SCB_EnableDCache();

    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_USART1_UART_Init();
    UART_Report_SetHandle(&huart1);
    UART_Report_Boot(AI_MODEL_NAME, AI_TARGET_BOARD, "EdgeAI_v1.0", 115200);

    uint32_t cycle = 0;

    while (1) {
        Poll_Uart_Command();
        Process_Uart_Command();

        float input[AI_INPUT_SIZE];
        if (Sensor_Read(input, AI_INPUT_SIZE) != HAL_OK) {
            HAL_Delay(50);
            continue;
        }

        Ensure_AI_Ready();
        AI_InferenceResult result;
        uint32_t inf_us = AI_Runner_Infer(input, &result);

        UART_Report_Inference(AI_MODEL_NAME, inf_us,
                              AI_Runner_GetRamUsage(),
                              result.confidence_pct,
                              result.label,
                              AI_TARGET_BOARD);
        UART_Report_Sensor(AI_SENSOR_TYPE,
                           cycle + 1,
                           (int32_t)(input[0] * 1000.0f),
                           (int32_t)(AI_INPUT_SIZE > 1 ? input[1] * 1000.0f : 0),
                           (int32_t)(AI_INPUT_SIZE > 2 ? input[2] * 1000.0f : 0),
                           "milli",
                           AI_MODEL_NAME,
                           inf_us,
                           AI_Runner_GetRamUsage(),
                           result.confidence_pct,
                           result.label,
                           AI_TARGET_BOARD);

        if (++cycle % 60 == 0) {
            UART_Report_SysStatus(cycle / 60,
                                  0,
                                  AI_Runner_GetFreeRam(),
                                  "running");
            HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
        }

        HAL_Delay(16);
    }
}

static void Ensure_AI_Ready(void)
{
    if (!s_ai_ready) {
        AI_Runner_Init();
        s_ai_ready = 1;
    }
}

/* ── Benchmark (BENCH command) ─────────────────────────────────────────────── */
static uint32_t bench_rand(uint32_t *state)
{
    *state = (*state * 1664525UL) + 1013904223UL;
    return *state;
}

static void Run_Benchmark(uint32_t samples, float min_v, float max_v, uint32_t seed)
{
    Ensure_AI_Ready();

    if (samples == 0) samples = 1;
    if (samples > 10000) samples = 10000;
    if (max_v < min_v) { float t = min_v; min_v = max_v; max_v = t; }

    uint32_t total_us = 0, min_us = 0xFFFFFFFFUL, max_us = 0;
    AI_InferenceResult result = {0};
    float input[AI_INPUT_SIZE];
    uint32_t rng = seed ? seed : 1;

    for (uint32_t i = 0; i < samples; ++i) {
        for (uint32_t j = 0; j < AI_INPUT_SIZE; ++j) {
            float unit = (float)(bench_rand(&rng) & 0x00FFFFFFu) / 16777215.0f;
            input[j] = min_v + unit * (max_v - min_v);
        }
        uint32_t t = AI_Runner_Infer(input, &result);
        total_us += t;
        if (t < min_us) min_us = t;
        if (t > max_us) max_us = t;
    }

    UART_Report_Benchmark(AI_MODEL_NAME, samples,
                          total_us / samples, min_us, max_us,
                          AI_Runner_GetRamUsage(), AI_Runner_GetFreeRam(),
                          result.label, AI_TARGET_BOARD);
}

/* ── INFER command ─────────────────────────────────────────────────────────── */
static void Run_Manual_Inference(const char *payload)
{
    Ensure_AI_Ready();

    float input[AI_INPUT_SIZE] = {0};
    const char *p = payload;

    for (uint32_t i = 0; i < AI_INPUT_SIZE; ++i) {
        while (*p == ' ' || *p == '\t' || *p == ',') ++p;
        if (*p == '\0') break;
        char *end = NULL;
        long milli = strtol(p, &end, 10);
        if (end == p) break;
        input[i] = (float)milli / 1000.0f;
        p = end;
    }

    AI_InferenceResult result = {0};
    uint32_t inf_us = AI_Runner_Infer(input, &result);
    UART_Report_Inference(AI_MODEL_NAME, inf_us,
                          AI_Runner_GetRamUsage(),
                          result.confidence_pct,
                          result.label,
                          AI_TARGET_BOARD);
}

/* ── UART command dispatcher ───────────────────────────────────────────────── */
static void Process_Uart_Command(void)
{
    if (!s_cmd_ready) return;

    char cmd[96];
    __disable_irq();
    memcpy(cmd, s_cmd_buf, sizeof(cmd));
    s_cmd_ready = 0;
    __enable_irq();

    unsigned long samples = 20;
    long min_milli = 0, max_milli = 1000;
    unsigned long seed = 1234;

    if (strncmp(cmd, "INFER ", 6) == 0) {
        Run_Manual_Inference(cmd + 6);
    } else if (sscanf(cmd, "BENCH %lu %ld %ld %lu",
                      &samples, &min_milli, &max_milli, &seed) >= 1) {
        Run_Benchmark((uint32_t)samples,
                      (float)min_milli / 1000.0f,
                      (float)max_milli / 1000.0f,
                      (uint32_t)seed);
    } else if (strcmp(cmd, "INFO?") == 0 || strcmp(cmd, "BOOT?") == 0) {
        UART_Report_Boot(AI_MODEL_NAME, AI_TARGET_BOARD, "EdgeAI_v1.0", 115200);
    }
}

static void Poll_Uart_Command(void)
{
    while ((USART1->ISR & USART_ISR_RXNE_RXFNE) != 0U) {
        Feed_Uart_Byte((uint8_t)(USART1->RDR & 0xFFU));
    }
}

static void Feed_Uart_Byte(uint8_t byte)
{
    char ch = (char)byte;
    if (!s_cmd_ready) {
        if (ch == '\r' || ch == '\n') {
            if (s_cmd_len > 0) {
                s_cmd_buf[s_cmd_len] = '\0';
                s_cmd_len   = 0;
                s_cmd_ready = 1;
            }
        } else if (s_cmd_len < sizeof(s_cmd_buf) - 1) {
            s_cmd_buf[s_cmd_len++] = ch;
        } else {
            s_cmd_len = 0;
        }
    }
}

/* ── UART RX ISR callbacks ─────────────────────────────────────────────────── */
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        Feed_Uart_Byte(s_rx_byte);
        HAL_UART_Receive_IT(&huart1, &s_rx_byte, 1);
    }
}

void HAL_UART_ErrorCallback(UART_HandleTypeDef *huart)
{
    if (huart->Instance == USART1) {
        s_cmd_len = 0;
        HAL_UART_Receive_IT(&huart1, &s_rx_byte, 1);
    }
}

/* ── System clock: HSI → PLL1 (N=75,M=4,P1=2) → 600 MHz CPU ────────────────
 * Based on STM32CubeN6 V1.2.0 NUCLEO-N657X0-Q example.
 * CPU: 600 MHz (IC1/2), SYSCLK AXI: 400 MHz (IC2/3), HCLK: 200 MHz        */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef osc = {0};
    RCC_ClkInitTypeDef clk = {0};

    /* Configure power supply */
    if (HAL_PWREx_ConfigSupply(PWR_EXTERNAL_SOURCE_SUPPLY) != HAL_OK)
        Error_Handler();

    /* Step 1: switch to HSI to allow PLL reconfiguration */
    osc.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    osc.HSIState            = RCC_HSI_ON;
    osc.HSIDiv              = RCC_HSI_DIV1;
    osc.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    osc.PLL1.PLLState       = RCC_PLL_NONE;
    osc.PLL2.PLLState       = RCC_PLL_NONE;
    osc.PLL3.PLLState       = RCC_PLL_NONE;
    osc.PLL4.PLLState       = RCC_PLL_NONE;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    /* Switch CPU/SYSCLK to HSI if currently on IC1/IC2 */
    HAL_RCC_GetClockConfig(&clk);
    if ((clk.CPUCLKSource == RCC_CPUCLKSOURCE_IC1) ||
        (clk.SYSCLKSource == RCC_SYSCLKSOURCE_IC2_IC6_IC11)) {
        clk.ClockType    = RCC_CLOCKTYPE_CPUCLK | RCC_CLOCKTYPE_SYSCLK;
        clk.CPUCLKSource = RCC_CPUCLKSOURCE_HSI;
        clk.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
        if (HAL_RCC_ClockConfig(&clk) != HAL_OK) Error_Handler();
    }

    /* Step 2: configure PLL1 — HSI 64 MHz / M=4 × N=75 = 1200 MHz VCO */
    osc.OscillatorType      = RCC_OSCILLATORTYPE_NONE;
    osc.PLL1.PLLState       = RCC_PLL_ON;
    osc.PLL1.PLLSource      = RCC_PLLSOURCE_HSI;
    osc.PLL1.PLLM           = 4;
    osc.PLL1.PLLN           = 75;
    osc.PLL1.PLLP1          = 1;
    osc.PLL1.PLLP2          = 1;
    osc.PLL1.PLLFractional  = 0;
    osc.PLL2.PLLState       = RCC_PLL_NONE;
    osc.PLL3.PLLState       = RCC_PLL_NONE;
    osc.PLL4.PLLState       = RCC_PLL_NONE;
    if (HAL_RCC_OscConfig(&osc) != HAL_OK) Error_Handler();

    /* Step 3: configure clocks
     *   IC1 = PLL1/2  → 600 MHz CPU
     *   IC2 = PLL1/3  → 400 MHz AXI
     *   IC6 = PLL1/4  → 300 MHz NPU
     *   IC11= PLL1/3  → 400 MHz AXISRAM */
    clk.ClockType       = RCC_CLOCKTYPE_CPUCLK | RCC_CLOCKTYPE_HCLK  |
                          RCC_CLOCKTYPE_SYSCLK  | RCC_CLOCKTYPE_PCLK1 |
                          RCC_CLOCKTYPE_PCLK2   | RCC_CLOCKTYPE_PCLK4 |
                          RCC_CLOCKTYPE_PCLK5;
    clk.CPUCLKSource    = RCC_CPUCLKSOURCE_IC1;
    clk.SYSCLKSource    = RCC_SYSCLKSOURCE_IC2_IC6_IC11;
    clk.AHBCLKDivider   = RCC_HCLK_DIV2;
    clk.APB1CLKDivider  = RCC_APB1_DIV1;
    clk.APB2CLKDivider  = RCC_APB2_DIV1;
    clk.APB4CLKDivider  = RCC_APB4_DIV1;
    clk.APB5CLKDivider  = RCC_APB5_DIV1;
    clk.IC1Selection.ClockSelection  = RCC_ICCLKSOURCE_PLL1;
    clk.IC1Selection.ClockDivider    = 2;
    clk.IC2Selection.ClockSelection  = RCC_ICCLKSOURCE_PLL1;
    clk.IC2Selection.ClockDivider    = 3;
    clk.IC6Selection.ClockSelection  = RCC_ICCLKSOURCE_PLL1;
    clk.IC6Selection.ClockDivider    = 4;
    clk.IC11Selection.ClockSelection = RCC_ICCLKSOURCE_PLL1;
    clk.IC11Selection.ClockDivider   = 3;
    if (HAL_RCC_ClockConfig(&clk) != HAL_OK) Error_Handler();
}

/* ── GPIO: LED1 on PG8 ─────────────────────────────────────────────────────── */
static void MX_GPIO_Init(void)
{
    __HAL_RCC_GPIOG_CLK_ENABLE();
    __HAL_RCC_GPIOE_CLK_ENABLE();

    GPIO_InitTypeDef gpio = {0};
    gpio.Pin   = LED_PIN;
    gpio.Mode  = GPIO_MODE_OUTPUT_PP;
    gpio.Pull  = GPIO_NOPULL;
    gpio.Speed = GPIO_SPEED_FREQ_LOW;
    HAL_GPIO_Init(LED_PORT, &gpio);
    HAL_GPIO_WritePin(LED_PORT, LED_PIN, GPIO_PIN_RESET);

}

/* ── USART1: ST-Link VCP — TX=PE5, RX=PE6 ─────────────────────────────────── */
static void MX_USART1_UART_Init(void)
{
    huart1.Instance          = USART1;
    huart1.Init.BaudRate     = 115200;
    huart1.Init.WordLength   = UART_WORDLENGTH_8B;
    huart1.Init.StopBits     = UART_STOPBITS_1;
    huart1.Init.Parity       = UART_PARITY_NONE;
    huart1.Init.Mode         = UART_MODE_TX_RX;
    huart1.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart1.Init.OverSampling = UART_OVERSAMPLING_16;
    huart1.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart1.Init.ClockPrescaler = UART_PRESCALER_DIV1;
    huart1.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    if (HAL_UART_Init(&huart1) != HAL_OK) Error_Handler();
    if (HAL_UARTEx_SetTxFifoThreshold(&huart1, UART_TXFIFO_THRESHOLD_1_8) != HAL_OK) Error_Handler();
    if (HAL_UARTEx_SetRxFifoThreshold(&huart1, UART_RXFIFO_THRESHOLD_1_8) != HAL_OK) Error_Handler();
    if (HAL_UARTEx_DisableFifoMode(&huart1) != HAL_OK) Error_Handler();
}

/* ── I2C1: sensor bus ──────────────────────────────────────────────────────── */
static void MX_I2C1_Init(void)
{
    hi2c1.Instance              = {{I2C_INSTANCE}};
    hi2c1.Init.Timing           = 0x00C0EAFF;
    hi2c1.Init.OwnAddress1      = 0;
    hi2c1.Init.AddressingMode   = I2C_ADDRESSINGMODE_7BIT;
    hi2c1.Init.DualAddressMode  = I2C_DUALADDRESS_DISABLE;
    hi2c1.Init.OwnAddress2      = 0;
    hi2c1.Init.OwnAddress2Masks = I2C_OA2_NOMASK;
    hi2c1.Init.GeneralCallMode  = I2C_GENERALCALL_DISABLE;
    hi2c1.Init.NoStretchMode    = I2C_NOSTRETCH_DISABLE;
    if (HAL_I2C_Init(&hi2c1) != HAL_OK) Error_Handler();
    if (HAL_I2CEx_ConfigAnalogFilter(&hi2c1, I2C_ANALOGFILTER_ENABLE) != HAL_OK) Error_Handler();
    if (HAL_I2CEx_ConfigDigitalFilter(&hi2c1, 0) != HAL_OK) Error_Handler();
}

void Error_Handler(void)
{
    __disable_irq();
    while (1) {
        HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
        for (volatile uint32_t i = 0; i < 2000000UL; ++i) {
            __NOP();
        }
    }
}
