/* pdm_mic.c — PDM Microphone driver via SAI
 * Protocol: SAI @ {{SAI_INSTANCE}}, CLK={{CLK_PORT}} {{CLK_PIN}}, DATA={{DATA_PORT}} {{DATA_PIN}}
 * Auto-generated by STM32 AI Deployer.
 *
 * NOTE: PDM→PCM decimation requires either:
 *   (a) STM32 PDM library (Middlewares/ST/STM32_Audio/PDM2PCM), or
 *   (b) Custom CIC/Polyphase filter.
 * This template uses a placeholder decimation — replace with your library.
 */

#include "pdm_mic.h"
#include <string.h>
#include <math.h>

static SAI_HandleTypeDef *s_hsai = NULL;
static PDM_AudioFrame     s_frame;

/* ── Init ─────────────────────────────────────────────────────────────── */

HAL_StatusTypeDef PDM_Mic_Init(SAI_HandleTypeDef *hsai)
{
    s_hsai = hsai;

    /* GPIO: CLK and DATA pins already configured in MspInit */
    /* Enable SAI clock in MspInit before calling HAL_SAI_Init */

    hsai->Instance                    = {{SAI_INSTANCE}};  /* SAI1 Block A */
    hsai->Init.AudioMode              = SAI_MODESLAVE_RX;
    hsai->Init.Synchro                = SAI_ASYNCHRONOUS;
    hsai->Init.OutputDrive            = SAI_OUTPUTDRIVE_DISABLE;
    hsai->Init.NoDivider              = SAI_MASTERDIVIDER_DISABLE;
    hsai->Init.FIFOThreshold          = SAI_FIFOTHRESHOLD_EMPTY;
    hsai->Init.AudioFrequency         = SAI_AUDIO_FREQUENCY_MUXER;
    hsai->Init.Protocol               = SAI_FREE_PROTOCOL;
    hsai->Init.DataSize               = SAI_DATASIZE_16;
    hsai->Init.FirstBit               = SAI_FIRSTBIT_MSB;
    hsai->Init.ClockStrobing          = SAI_CLOCKSTROBING_RISINGEDGE;

    hsai->FrameInit.FrameLength       = 16;
    hsai->FrameInit.ActiveFrameLength = 1;
    hsai->FrameInit.FSDefinition      = SAI_FS_STARTFRAME;
    hsai->FrameInit.FSPolarity        = SAI_FS_ACTIVE_HIGH;
    hsai->FrameInit.FSOffset          = SAI_FS_FIRSTBIT;

    hsai->SlotInit.FirstBitOffset     = 0;
    hsai->SlotInit.SlotSize           = SAI_SLOTSIZE_DATASIZE;
    hsai->SlotInit.SlotNumber         = 1;
    hsai->SlotInit.SlotActive         = SAI_SLOTACTIVE_0;

    return HAL_SAI_Init(hsai);
}

/* ── Capture PCM data ─────────────────────────────────────────────────── */

HAL_StatusTypeDef PDM_Mic_Capture(SAI_HandleTypeDef *hsai, PDM_AudioFrame *frame)
{
    /* Blocking DMA receive — replace with interrupt/DMA for production */
    return HAL_SAI_Receive(hsai, (uint8_t *)frame->pcm,
                           PDM_BUFFER_SIZE * 2, 50);
}

/* ── MFCC (placeholder — integrate DSP library) ───────────────────────── */

void PDM_Mic_ComputeMFCC(const int16_t *pcm, float *mfcc, uint16_t len)
{
    /* PLACEHOLDER: Replace with arm_rfft_fast_f32 + mel filterbank + DCT.
     * For now, output normalised RMS energy per bin as a stub. */
    float energy = 0.0f;
    for (uint16_t i = 0; i < len; i++) {
        float s = (float)pcm[i] / 32768.0f;
        energy += s * s;
    }
    energy = sqrtf(energy / len);

    for (uint16_t c = 0; c < MFCC_NUM_COEFFS; c++)
        mfcc[c] = energy * (c == 0 ? 1.0f : 0.1f * (MFCC_NUM_COEFFS - c));
}

/* ── Generic Sensor API ───────────────────────────────────────────────── */

void Sensor_Init(I2C_HandleTypeDef *hi2c)
{
    (void)hi2c;  /* PDM mic does not use I2C */

    /* SAI handle must be initialised in main before calling this */
}

void Sensor_Read(float *out, uint16_t len)
{
    if (!s_hsai) { memset(out, 0, len * sizeof(float)); return; }

    PDM_Mic_Capture(s_hsai, &s_frame);
    PDM_Mic_ComputeMFCC(s_frame.pcm, s_frame.mfcc, PDM_BUFFER_SIZE);

    uint16_t copy = (len < MFCC_NUM_COEFFS) ? len : MFCC_NUM_COEFFS;
    memcpy(out, s_frame.mfcc, copy * sizeof(float));
    for (uint16_t i = copy; i < len; i++) out[i] = 0.0f;
}
